language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - libgdal-dev
      - python-dev
      - build-essential

install:
  - "pip install --upgrade pip setuptools wheel"
  - "pip install --only-binary=numpy,scipy numpy scipy"
  - "pip install -r requirements-dev.txt"
  - "pip install -r requirements.txt"
  - "pip install -e ."

script: pytest


